apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "npdbchart.fullname" . }}-nginx-conf
  labels:
    {{- include "npdbchart.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;

    events {
        worker_connections 1024;
    }

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        log_format main_with_cache '$remote_addr - $remote_user [$time_local] '
                                    '"$request" $status $body_bytes_sent '
                                    '"$http_referer" "$http_user_agent" '
                                    '$upstream_cache_status';

        access_log /dev/stdout main_with_cache;
        error_log /dev/stderr warn;

        # Shared Cache Configuration
        proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=my_cache:50m max_size=500m inactive=1h use_temp_path=off;

        # API Upstreams
        upstream django {
            server {{ include "npdbchart.fullname" . }}-django.{{ .Values.project }}.svc.cluster.local:8000 max_conns=2000;
        }

        client_max_body_size 100M;

        # --- Metadata API Proxy ---
        server {
            listen 8080;
            server_name {{ .Values.appname }}.{{ .Values.domain }};

            proxy_hide_header Cache-Control;
            add_header Cache-Control {{ .Values.nginx_cache_control_value | quote }};
            add_header X-Cache-Status $upstream_cache_status;
            proxy_cache my_cache;
            proxy_ignore_headers "Cache-Control" "Expires";

            proxy_read_timeout 1800;
            proxy_connect_timeout 1800;
            proxy_send_timeout 1800;

            location / {
                proxy_pass http://django;
                proxy_redirect off;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "npdbchart.fullname" . }}-nginx
  labels:
    {{- include "npdbchart.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "npdbchart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: nginx
  template:
    metadata:
      labels:
        {{- include "npdbchart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: nginx
    spec:
      securityContext:
        runAsUser: 101
        fsGroup: 1000860000
      volumes:
        - name: files-volume
          persistentVolumeClaim:
            claimName: {{ .Values.pvc_payload_server }}
        - name: nginx-conf-volume
          configMap:
            name: {{ include "npdbchart.fullname" . }}-nginx-conf
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-pid
          emptyDir: {}
      containers:
        - name: nginx
          image: {{ .Values.nginx_docker_image }}
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: files-volume
              mountPath: /usr/share/nginx/html
              subPath: {{ .Values.subPath }}
            - name: nginx-conf-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-pid
              mountPath: /var/run
          imagePullPolicy: IfNotPresent
---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "npdbchart.fullname" . }}-nginx
  labels:
    {{- include "npdbchart.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  selector:
    {{- include "npdbchart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "npdbchart.fullname" . }}-nginx
  labels:
    {{- include "npdbchart.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: {{ .Values.appname }}.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "npdbchart.fullname" . }}-nginx
                port:
                  name: http
  tls:
    - hosts:
        - {{ .Values.appname }}.{{ .Values.domain }}
