{{- if not .Values.use_java }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "npdbchart.fullname" . }}-django
  labels:
    {{- include "npdbchart.labels" . | nindent 4 }}
    app.kubernetes.io/component: django
spec:
  lookupPolicy:
    local: true
  tags:
    - name: {{ .Values.django_docker_image | splitList ":" | last | quote }}
      from:
        kind: DockerImage
        name: {{ .Values.django_docker_image }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "npdbchart.fullname" . }}-django
  labels:
    {{- include "npdbchart.labels" . | nindent 4 }}
    app.kubernetes.io/component: django
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "npdbchart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: django
  template:
    metadata:
      labels:
        {{- include "npdbchart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: django
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - {{ .Values.exclude_node }}
      containers:
      - name: django
        image: "image-registry.openshift-image-registry.svc:5000/{{ .Values.project }}/{{ include "npdbchart.fullname" . }}-django:{{ .Values.django_docker_image | splitList ":" | last }}"
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8080
          protocol: TCP
        {{- if .Values.migrations_enabled }}
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - python3 manage.py makemigrations cdb_rest; python3 manage.py migrate cdb_rest
        {{- end }}
        env:
        - name: POSTGRES_HOST_W
          value: {{ if .Values.use_pgbouncer }}{{ include "npdbchart.fullname" . }}-pgbouncer.{{ .Values.project }}.svc.cluster.local{{ else }}{{ .Values.dbhost_w }}{{ end }}
        - name: POSTGRES_DB_W
          value: {{ .Values.dbname_w }}
        - name: POSTGRES_USER_W
          value: {{ .Values.dbuser_w }}
        - name: POSTGRES_PASSWORD_W
          value: {{ .Values.dbpassword_w }}
        - name: POSTGRES_PORT_W
          value: {{ if .Values.use_pgbouncer }}"6432"{{ else }}"5432"{{ end }}
        - name: POSTGRES_HOST_R1
          value: {{ if .Values.use_pgbouncer }}{{ include "npdbchart.fullname" . }}-pgbouncer.{{ .Values.project }}.svc.cluster.local{{ else }}{{ .Values.dbhost_r1 }}{{ end }}
        - name: POSTGRES_DB_R1
          value: {{ .Values.dbname_r1 }}
        - name: POSTGRES_USER_R1
          value: {{ .Values.dbuser_r1 }}
        - name: POSTGRES_PASSWORD_R1
          value: {{ .Values.dbpassword_r1 }}
        - name: POSTGRES_PORT_R1
          value: {{ if .Values.use_pgbouncer }}"6432"{{ else }}"5432"{{ end }}
        - name: POSTGRES_HOST_R2
          value: {{ if .Values.use_pgbouncer }}{{ include "npdbchart.fullname" . }}-pgbouncer.{{ .Values.project }}.svc.cluster.local{{ else }}{{ .Values.dbhost_r2 }}{{ end }}
        - name: POSTGRES_DB_R2
          value: {{ .Values.dbname_r2 }}
        - name: POSTGRES_USER_R2
          value: {{ .Values.dbuser_r2 }}
        - name: POSTGRES_PASSWORD_R2
          value: {{ .Values.dbpassword_r2 }}
        - name: POSTGRES_PORT_R2
          value: {{ if .Values.use_pgbouncer }}"6432"{{ else }}"5432"{{ end }}
        volumeMounts:
        - name: run
          mountPath: /var/run
        - name: varlog
          mountPath: /var/log
      {{- if .Values.promtail_enabled }}
      - name: promtail
        image: grafana/promtail:2.9.0
        args:
          - "-config.file=/etc/promtail/promtail-config.yaml"
        volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: promtail-config
            mountPath: /etc/promtail
      {{- end }}
      volumes:
        - name: run
          emptyDir: {}
        - name: varlog
          emptyDir: {}
        {{- if .Values.promtail_enabled }}
        - name: promtail-config
          configMap:
            name: promtail-config
        {{- end }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "npdbchart.fullname" . }}-django
  labels:
    {{- include "npdbchart.labels" . | nindent 4 }}
    app.kubernetes.io/component: django
spec:
  selector:
    {{- include "npdbchart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: django
  ports:
    - name: "tcp-8000"
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
{{- end }}
