apiVersion: apps/v1
kind: Deployment
metadata:
  name: b2testpsql
  namespace: belle2-cdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: b2testpsql
  template:
    metadata:
      labels:
        app: b2testpsql
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: b2testpsql
          image: registry.redhat.io/rhel9/postgresql-15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_DATABASE
              value: # specify your database name
            - name: POSTGRESQL_USER
              value: # specify your database user
            - name: POSTGRESQL_PASSWORD
              value: # specify your database password, it's explicit and not secure, consider using Secrets for production
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "4"
              memory: "8Gi"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/pgsql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: b2testpsql
---
apiVersion: v1
kind: Service
metadata:
  name: b2testpsql
  namespace: belle2-cdb
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: b2testpsql