apiVersion: v1
kind: Secret
metadata:
  name: b2testpsql-exporter-dsn
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  dsn: postgresql://${POSTGRESQL_USER}:${POSTGRESQL_PASSWORD}@127.0.0.1:5432/${POSTGRESQL_DATABASE}?sslmode=disable
